import {test} from 'node:test';import assert from 'node:assert/strict';
import {fixture,withEvent} from './fixture.mjs';import {auditBundle,prepareBundle} from '../dist/quality.mjs';import {backtest,defaults,compareParameters,qualityScore,wilson} from '../dist/engine.mjs';import {boardRule,buyQuantity,knownLimits} from '../dist/rules.mjs';import {CorporateLedger} from '../dist/corporate.mjs';
const config=b=>({...defaults,capital:100000,strategy:'ma',timeframe:'5m',from:b.calendar[40],to:b.calendar.at(-1),fast:2,slow:3,taxMode:'manual',management:'base',handling:0,regulatory:0,commission:0,minCommission:0,transfer:0,stamp:0,slippage:0,stop:8,take:0});
test('board quantity and historical price limits use historical dates',()=>{
 assert.equal(boardRule('chinext','2020-08-21').pct,10);assert.equal(boardRule('chinext','2020-08-24').pct,20);assert.equal(boardRule('main','2026-07-03',1).pct,5);assert.equal(boardRule('main','2026-07-06',1).pct,10);assert.equal(boardRule('star','2024-01-01',1).pct,20);assert.equal(boardRule('bse','2024-01-01',1).pct,30);
 assert.equal(buyQuantity(1990,10,boardRule('star','2024-01-01')),0);assert.equal(buyQuantity(2370,10,boardRule('star','2024-01-01')),237);assert.equal(buyQuantity(1370,10,boardRule('bse','2024-01-01')),137);assert.equal(buyQuantity(1370,10,boardRule('main','2024-01-01')),100);
 assert.equal(boardRule('star','2024-01-02',0,3,'2024-01-01').noLimit,true);assert.equal(boardRule('main','2024-01-02',0,3,'2024-01-01').noLimit,true);assert.equal(boardRule('bse','2024-01-02',0,2,'2024-01-01').noLimit,false);
 assert.equal(knownLimits({date:'2024-01-01',board:'main'},10.05,defaults).up,11.06);
});
test('full bundle verifies independent day grid, ST, factors and historical membership',()=>{const b=fixture(),q=auditBundle(b);assert.equal(q.status,'passed',JSON.stringify(q.issues));assert.equal(q.completeSessions,90);assert.equal(prepareBundle(b).bars[0].isHS300,1);});
test('single-security backtest uses collected raw data without fabricating index membership',()=>{
 const b=withEvent(fixture(120));b.metadata.universe='SINGLE_SECURITY';b.metadata.collectionPurpose='market-data-only';b.metadata.coverage.universe={status:'not-requested'};b.universe=[];
 const bytes=JSON.stringify(b),c={...config(b),dataMode:'single',snapshotId:'a'.repeat(64)};
 assert.equal(auditBundle(b).status,'blocked');assert.throws(()=>backtest(b,{...c,dataMode:'formal'}),/数据准入/);
 for(const timeframe of ['5m','15m','1d']){const r=backtest(b,{...c,timeframe});assert.ok(r.trades.some(t=>t.side==='买入'));assert.ok(r.corporateEvents.some(e=>e.event==='股息到账'));assert.equal(r.audit.qualityReport.scope,'single-security');assert.equal(r.audit.qualityReport.membershipChecked,false);assert.equal(r.audit.snapshotId,c.snapshotId);assert.ok(r.trades.every(t=>t.signalTime<=t.executionTime));assert.ok(r.trades.every(t=>t.executionTime.slice(0,10)>=c.from));assert.ok(r.warnings.some(w=>w.includes('未核验')));assert.deepEqual(r,backtest(b,{...c,timeframe}));}
 assert.equal(JSON.stringify(b),bytes);assert.throws(()=>backtest(b.bars,c),/完整数据包/);
});
test('single-security admission retains minute, ST, suspension and corporate-action checks',()=>{
 for(const mutate of [b=>b.bars.splice(50,1),b=>{b.bars=b.bars.filter(r=>!r.date.startsWith(b.calendar[50]));},b=>delete b.daily[20].isST,b=>b.daily[20].knownAt=b.calendar[21]+' 09:00',b=>delete b.daily[20].halted,b=>delete b.metadata.coverage.actions,b=>{withEvent(b);delete b.actions[0].payDate;},b=>b.actions.push({id:'rights',type:'rights',exDate:b.calendar[30],rightsPerShare:.2}),b=>b.metadata.conflicts=[{date:b.calendar[2]}]]){const b=fixture(120);b.metadata.universe='SINGLE_SECURITY';b.universe=[];mutate(b);assert.equal(auditBundle(b,{scope:'single-security'}).status,'blocked');assert.throws(()=>backtest(b,{...config(b),dataMode:'single'}),/数据准入/);}
 const b=fixture(120);b.metadata.universe='SINGLE_SECURITY';b.universe=[];for(const d of b.daily)if(d.date>=b.calendar[45])d.isST=1;
 const r=backtest(b,{...config(b),dataMode:'single'});assert.equal(r.trades.filter(t=>t.side==='买入').length,1);assert.equal(r.trades.find(t=>t.side==='卖出').executionTime,b.calendar[45]+' 09:30');
});
test('missing whole session and minute, unknown ST, future membership and revised overlaps block formal runs',()=>{for(const mutate of [b=>{b.bars=b.bars.filter(x=>!x.date.startsWith(b.calendar[45]));},b=>b.bars.splice(50,1),b=>delete b.daily[20].isST,b=>b.universe[20].updateDate='2099-01-01',b=>b.metadata.conflicts=[{date:b.calendar[2]}]]){const b=fixture();mutate(b);assert.equal(auditBundle(b).status,'blocked');assert.throws(()=>backtest(b,config(b)),/数据准入/);}});
test('today member list cannot replace historical snapshots; rights and missing payouts fail closed',()=>{for(const mutate of [b=>{b.universe=[b.universe.at(-1)];},b=>{b.actions=[{id:'rights',type:'rights',exDate:b.calendar[30],rightsPerShare:.2}];},b=>{withEvent(b);delete b.actions[0].payDate;}]){const b=fixture();mutate(b);assert.equal(auditBundle(b).status,'blocked');}});
test('historical ST and HS300 removal exit existing position; re-entry prohibited during exclusion',()=>{for(const kind of ['ST','INDEX']){const b=fixture();const day=b.calendar[45];if(kind==='ST')for(const d of b.daily)if(d.date>=day)d.isST=1;else{}else for(const u of b.universe)if(u.date>=day)u.codes=u.codes.map(x=>x==='sh.600519'?'sh.600999':x);const r=backtest(b,config(b));const sell=r.trades.find(t=>t.side==='卖出');assert.ok(sell);assert.equal(sell.executionTime,day+' 09:30');assert.equal(r.trades.filter(t=>t.side==='买入').length,1);}});
test('dividend receivables and locked bonus preserve equity without premature spending or sales',()=>{const b=withEvent(fixture());const q=auditBundle(b);assert.equal(q.status,'passed',JSON.stringify(q.issues));const r=backtest(b,config(b)),pre=r.curve.filter(x=>x.date.startsWith(b.calendar[49])).at(-1),ex=r.curve.find(x=>x.date.startsWith(b.calendar[50]));assert.ok(ex.receivable>0);assert.ok(ex.lockedQuantity>0);assert.equal(ex.cash,pre.cash);assert.equal(ex.quantity,pre.quantity);assert.ok(r.trades.every(x=>x.reason!=='前根收盘止损'),'mechanical ex-gap must not trigger stop');assert.ok(Math.abs(ex.equity-pre.equity)<30,'flooring fractional bonus can cause a small economic residual, not a false 20% loss');const paid=r.curve.find(x=>x.date.startsWith(b.calendar[53]));assert.equal(paid.receivable,0);assert.ok(paid.cash>ex.cash);const listed=r.curve.find(x=>x.date.startsWith(b.calendar[55]));assert.equal(listed.lockedQuantity,0);assert.ok(listed.quantity>ex.quantity);assert.ok(r.corporateEvents.some(x=>x.event==='股息到账'));});
test('entitlements survive sale before payout and settle closed PnL only after locked assets finish',()=>{const b=withEvent(fixture(),50,{cash:1,bonus:.2,payDelay:3,listDelay:5});for(const d of b.daily)if(d.date>=b.calendar[51])d.isST=1;const r=backtest(b,config(b));assert.ok(r.trades.some(x=>x.side==='卖出'&&x.executionTime.startsWith(b.calendar[51])));assert.equal(r.closed.length,1);const buys=r.trades.filter(x=>x.side==='买入').reduce((s,t)=>s+t.amount+t.fee,0),sales=r.trades.filter(x=>x.side==='卖出').reduce((s,t)=>s+t.amount-t.fee,0),div=r.corporateEvents.filter(x=>x.event==='股息到账').reduce((s,t)=>s+t.amount,0);assert.ok(Math.abs(r.closed[0].pnl-(sales+div-buys))<1e-6);});
test('future ex-events and future members cannot change earlier fills/equity',()=>{const b=fixture(),first=backtest(b,config(b)),changed=withEvent(structuredClone(b),70);changed.universe.filter(u=>u.date>=b.calendar[80]).forEach(u=>{u.codes=u.codes.map(x=>x==='sh.600519'?'sh.600999':x);});const second=backtest(changed,config(changed)),cut=b.calendar[70];assert.deepEqual(first.curve.filter(x=>x.date<cut),second.curve.filter(x=>x.date<cut));assert.deepEqual(first.trades.filter(x=>x.executionTime<cut),second.trades.filter(x=>x.executionTime<cut));});
test('trade quality rejects small winning samples and uses only training results',()=>{const c={...defaults,minTrades:20},m={closedTrades:2,total:1,expectancy:100,winrate:1,profitFactor:null,maxdd:0,wilsonLower:wilson(2,2)};assert.equal(qualityScore(m,c).eligible,false);assert.ok(wilson(2,2)<.5);const b=fixture(230),params={...config(b),strategy:'swing',timeframe:'15m',from:b.calendar[125],maxExtensionATR:10},r=compareParameters(b,params);assert.equal(r.selectionRule,'training_quality_only');const changed=structuredClone(b);changed.universe.filter(u=>u.date>=r.validationFrom).forEach(u=>{u.codes=u.codes.map(x=>x==='sh.600519'?'sh.600999':x);});const r2=compareParameters(changed,params);assert.deepEqual(r.rows.map(x=>[x.config.dailySlow,x.config.atrMult,x.quality,x.training]),r2.rows.map(x=>[x.config.dailySlow,x.config.atrMult,x.quality,x.training]));});
test('same-day weekly member refresh is unavailable at open and cannot cause a same-day order',()=>{const b=fixture();for(const u of b.universe)if(u.date>=b.calendar[45]){u.codes=u.codes.map(x=>x==='sh.600519'?'sh.600999':x);u.updateDate=b.calendar[45];u.knownAt=b.calendar[45]+' 15:00';}const r=backtest(b,config(b)),sell=r.trades.find(t=>t.side==='卖出');assert.equal(sell.executionTime,b.calendar[46]+' 09:30');});
test('verified suspension without minute candles carries valuation and pays existing claims, with no fabricated fill',()=>{const b=withEvent(fixture());const day=b.calendar[53];b.bars=b.bars.filter(r=>!r.date.startsWith(day));const d=b.daily[53];d.halted=1;d.close=b.daily[52].close;d.volume=0;d.prev_close=d.close;
 // Next traded reference and causal factor are still tied to the last available close.
 b.daily[54].prev_close=d.close;const afterRatio=d.close/b.daily[54].prev_close;assert.equal(afterRatio,1);const r=backtest(b,config(b)),point=r.curve.find(x=>x.date.startsWith(day));assert.ok(point.valuationOnly);assert.equal(point.receivable,0);assert.ok(!r.trades.some(x=>x.executionTime.startsWith(day)));assert.equal(r.period.valuationPoints,1);assert.equal(r.period.tradingDays,50);});
