import {test} from 'node:test';import assert from 'node:assert/strict';
import {backtest,defaults,parseCSV,demoMinuteData} from '../dist/engine.mjs';import {auditBundle} from '../dist/quality.mjs';
import {executionTime} from '../dist/data.mjs';
import {auditAccounting} from '../server/research.mjs';import {fixture} from './fixture.mjs';
const config=b=>({...defaults,dataMode:'single',capital:100000,strategy:'ma',fast:2,slow:3,management:'base',from:b.calendar[65],to:b.calendar.at(-1),timeframe:'5m',stop:8,take:0,slippage:0});
const bundle=()=>{const b=fixture(100);Object.assign(b.metadata,{universe:'SINGLE_SECURITY',collectionPurpose:'market-data-only'});b.universe=[];return b;};
const intent=o=>Object.fromEntries(['submittedAt','signalTime','dailySignalTime','side','purpose','requestedQuantity','estimatedPrice'].map(k=>[k,o[k]]));
const zero=(b,index)=>{const r=b.bars[index],day=r.date.slice(0,10),v=r.volume;r.volume=0;b.daily.find(d=>d.date===day).volume-=v;return r;};

test('CSV accepts zero print candles, preserves explicit 0 and unknown halt status and rejects negative volume',()=>{
 const h='datetime,open,high,low,close,volume,halted\n';const a=parseCSV(h+'2024-01-02 09:35,10,10,10,10,0,0\n2024-01-02 09:40,10,10,10,10,100,0');assert.equal(a[0].halted,0);assert.equal(a[0].volume,0);
 const b=parseCSV(h+'2024-01-02 09:35,10,10,10,10,0,\n2024-01-02 09:40,10,10,10,10,100,');assert.equal(b[0].halted,undefined);
 assert.throws(()=>parseCSV(h+'2024-01-02 09:35,10,10,10,10,-1,0\n2024-01-02 09:40,10,10,10,10,100,0'),/volume/);
});
test('zero liquidity changes the fill outcome, never the same opening order intent; no fees, no holdings, benchmark waits',()=>{
 const b=bundle(),c=config(b),baseline=backtest(b,c),first=baseline.trades[0],changed=structuredClone(b),r=zero(changed,65*48),before=JSON.stringify(changed),actual=backtest(changed,c);
 assert.deepEqual(intent(actual.orderAttempts[0]),intent(baseline.orderAttempts[0]));assert.equal(actual.orderAttempts[0].status,'unfilled');assert.equal(actual.orderAttempts[0].submittedAt,first.executionTime);assert.equal(actual.orderAttempts[0].resolvedAt,r.date);
 const p=actual.curve[0];assert.equal(p.cash,c.capital);assert.equal(p.quantity,0);assert.equal(p.benchmark,1);assert.ok(actual.trades.every(t=>t.executionTime!==first.executionTime));assert.equal(actual.trades[0].executionTime,r.date);assert.equal(actual.trades[0].confirmationTime,changed.bars[65*48+1].date);assert.equal(actual.metrics.fees,actual.trades.reduce((s,t)=>s+t.fee,0));assert.equal(actual.audit.orderDecisionSameBarVolumeUsed,false);assert.equal(actual.audit.sameBarVolumeUsed,true);assert.equal(JSON.stringify(changed),before);assert.equal(auditAccounting(actual,changed).status,'passed');assert.deepEqual(actual,backtest(changed,c));
});
test('zero first native 5m blocks an estimated aggregate opening fill even if 15m/daily total is positive',()=>{
 for(const timeframe of ['15m','1d']){const b=bundle(),c={...config(b),timeframe},original=backtest(b,c);zero(b,65*48);const actual=backtest(b,c);assert.deepEqual(intent(actual.orderAttempts[0]),intent(original.orderAttempts[0]));assert.equal(actual.orderAttempts[0].status,'unfilled');assert.equal(actual.orderAttempts[0].evidenceAvailableAt,b.calendar[65]+' 09:35');assert.equal(actual.orderAttempts[0].resolvedAt,b.calendar[65]+(timeframe==='1d'?' 15:00':' 09:45'));assert.equal(actual.curve[0].quantity,0);assert.ok(actual.trades[0].executionTime>=b.calendar[65]+(timeframe==='1d'?' 15:00':' 09:45'));assert.equal(auditAccounting(actual,b).status,'passed');}
});
test('a later zero native segment does not retroactively cancel a fill in an earlier positive opening segment',()=>{
 const b=bundle(),c={...config(b),timeframe:'15m'},before=backtest(b,c);zero(b,65*48+1);const actual=backtest(b,c);assert.deepEqual(actual.trades,before.trades);assert.equal(actual.orderAttempts[0].status,'filled');assert.equal(actual.orderAttempts[0].evidenceAvailableAt,b.calendar[65]+' 09:35');assert.equal(actual.dataInfo.zeroVolumeBars,1);
});
test('zero liquidity sell leaves FIFO inventory, pending risk exit and fees intact until a later real interval',()=>{
 const b=bundle(),c=config(b);for(const d of b.daily)if(d.date>=b.calendar[70])d.isST=1;const first=backtest(b,c),sell=first.trades.find(t=>t.side==='卖出'),r=zero(b,70*48),actual=backtest(b,c),prior=actual.curve.findLast(p=>p.date<r.date),point=actual.curve.find(p=>p.date===r.date);const failed=actual.orderAttempts.find(o=>o.submittedAt===sell.executionTime);assert.equal(failed.status,'unfilled');assert.equal(point.quantity,prior.quantity);assert.equal(point.cash,prior.cash);assert.equal(actual.trades.find(t=>t.side==='卖出').executionTime,r.date);assert.equal(actual.trades.find(t=>t.side==='卖出').signalTime,sell.signalTime);assert.equal(auditAccounting(actual,b).status,'passed');
});
test('ST/halt history, confirmed suspensions and missing minute grids still enforce their distinct rules',()=>{
 const b=bundle();zero(b,65*48);const q=auditBundle(b,{scope:'single-security'});assert.equal(q.status,'warning');assert.ok(q.warnings.some(i=>i.code==='ZERO_VOLUME_BARS'));assert.equal(q.blockingIssues.length,0);
 const halted=structuredClone(b);halted.daily[65].halted=1;for(const r of halted.bars.filter(r=>r.date.startsWith(halted.calendar[65]))){r.halted=1;r.volume=0;}halted.daily[65].volume=0;const price=halted.daily[64].close;Object.assign(halted.daily[65],{open:price,close:price,prev_close:price});halted.daily[66].prev_close=price;for(const r of halted.bars.filter(r=>r.date.startsWith(halted.calendar[65])))Object.assign(r,{open:price,high:price,low:price,close:price});const result=backtest(halted,config(halted));assert.ok(result.trades.every(t=>!t.executionTime.startsWith(halted.calendar[65])));assert.ok(result.orderAttempts.every(o=>!o.submittedAt.startsWith(halted.calendar[65])));
 for(const edit of [b=>delete b.daily[65].halted,b=>b.bars.splice(65*48,1),b=>delete b.daily[65].isST]){const bad=structuredClone(b);edit(bad);assert.equal(auditBundle(bad,{scope:'single-security'}).status,'blocked');assert.throws(()=>backtest(bad,config(bad)),/数据准入/);}
});
test('future volume changes leave every earlier order, trade and equity point unchanged',()=>{
 const b=bundle(),c=config(b),first=backtest(b,c),changed=structuredClone(b);zero(changed,80*48);const next=backtest(changed,c),cut=b.calendar[80];assert.deepEqual(first.curve.filter(p=>p.date<cut),next.curve.filter(p=>p.date<cut));assert.deepEqual(first.trades.filter(t=>t.executionTime<cut),next.trades.filter(t=>t.executionTime<cut));assert.deepEqual(first.orderAttempts.filter(o=>o.submittedAt<cut),next.orderAttempts.filter(o=>o.submittedAt<cut));
});
test('zero liquidity rolls back trend additions and both directions of T without retaining phantom inventory, fees or pair profits',()=>{
 const d=demoMinuteData(),c={...defaults,dataMode:'demo',management:'adaptive',riskBudget:5,tDeviation:.15,tTarget:.25,tCostBuffer:1},full=backtest(d,c);
 const targets=[full.trades.find(t=>t.purpose==='add'),...['positive','reverse'].flatMap(direction=>{const pair=full.tPairs.find(p=>p.direction===direction&&p.status==='paired');return [pair.first,pair.second];})];assert.ok(targets.every(Boolean));
 for(const target of targets){const changed=structuredClone(d),index=changed.findIndex(r=>executionTime(r,'5m')===target.executionTime);assert.ok(index>=0);changed[index].volume=0;const actual=backtest(changed,c),attempt=actual.orderAttempts.find(o=>o.submittedAt===target.executionTime&&o.purpose===target.purpose);assert.ok(attempt);assert.equal(attempt.status,'unfilled');assert.deepEqual(intent(attempt),intent(full.orderAttempts.find(o=>o.submittedAt===target.executionTime&&o.purpose===target.purpose)));assert.ok(actual.trades.every(t=>t.executionTime!==target.executionTime));const confirmation=attempt.resolvedAt,prior=actual.curve.findLast(p=>p.date<confirmation),point=actual.curve.find(p=>p.date===confirmation);assert.equal(point.cash,prior.cash);assert.equal(point.quantity,prior.quantity);assert.deepEqual(actual.trades.filter(t=>t.executionTime<target.executionTime),full.trades.filter(t=>t.executionTime<target.executionTime));assert.ok(Math.abs(actual.metrics.fees-actual.trades.reduce((s,t)=>s+t.fee,0))<1e-6);for(const t of actual.trades.filter(t=>t.side==='卖出'))assert.ok(t.quantity<=t.sellableBefore);for(const p of actual.tPairs.filter(p=>p.status==='paired'))assert.ok(actual.trades.includes(p.first)&&actual.trades.includes(p.second));}
});
